CREATE TABLE IF NOT EXISTS "Part" (
	"PartID" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"InventreeID" INTEGER,
	PRIMARY KEY("PartID")
);




CREATE TABLE IF NOT EXISTS "Grid" (
	"GridID" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"LocationID" INTEGER,
	"Name" TEXT,
	"Xmax" INTEGER NOT NULL,
	"Ymax" INTEGER NOT NULL,
	PRIMARY KEY("GridID")
);




CREATE TABLE IF NOT EXISTS "Location" (
	"LocationID" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" TEXT,
	"MasterLocationID" INTEGER,
	PRIMARY KEY("LocationID")
);




CREATE TABLE IF NOT EXISTS "Bin" (
	"BinID" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"BinTypeID" INTEGER NOT NULL,
	PRIMARY KEY("BinID")
);




CREATE TABLE IF NOT EXISTS "BinSlot" (
	"BinID" INTEGER NOT NULL,
	"PartID" INTEGER NOT NULL,
	"SlotNr" INTEGER NOT NULL,
	PRIMARY KEY("BinID", "SlotNr")
);




CREATE TABLE IF NOT EXISTS "BinType" (
	"BinTypeID" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"SlotCount" INTEGER NOT NULL,
	"X" INTEGER NOT NULL,
	"Y" INTEGER NOT NULL,
	PRIMARY KEY("BinTypeID")
);




CREATE TABLE IF NOT EXISTS "GridPos" (
	"GridPosID" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"X" INTEGER NOT NULL,
	"Y" INTEGER NOT NULL,
	"BinID" INTEGER NOT NULL,
	"GridID" INTEGER NOT NULL,
	PRIMARY KEY("GridPosID")
);



ALTER TABLE "BinSlot"
ADD FOREIGN KEY("BinID") REFERENCES "Bin"("BinID")
ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "BinSlot"
ADD FOREIGN KEY("PartID") REFERENCES "Part"("PartID")
ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "Bin"
ADD FOREIGN KEY("BinTypeID") REFERENCES "BinType"("BinTypeID")
ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "Location"
ADD FOREIGN KEY("MasterLocationID") REFERENCES "Location"("LocationID")
ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "Grid"
ADD FOREIGN KEY("LocationID") REFERENCES "Location"("LocationID")
ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "GridPos"
ADD FOREIGN KEY("BinID") REFERENCES "Bin"("BinID")
ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "GridPos"
ADD FOREIGN KEY("GridID") REFERENCES "Grid"("GridID")
ON UPDATE CASCADE ON DELETE RESTRICT;


INSERT INTO "Location" ("LocationID", "name", "MasterLocationID")
VALUES
  (1, 'Root', NULL),
  (2, 'Testlager', 1),
  (3, 'Testsschubladen', 2)
ON CONFLICT ("LocationID") DO NOTHING;

INSERT INTO "Grid" ("GridID", "LocationID", "Name", "Xmax", "Ymax")
VALUES
  (1, 2, 'Oberste Schublade',3,4)
ON CONFLICT ("GridID") DO NOTHING;

INSERT INTO "BinType" ("BinTypeID", "SlotCount", "X", "Y")
VALUES
  (1, 1, 1, 1),
  (2, 3, 2, 1)
ON CONFLICT ("BinTypeID") DO NOTHING;

INSERT INTO "Bin" ("BinID", "BinTypeID")
VALUES
  (1, 1),
  (2, 2)
ON CONFLICT ("BinID") DO NOTHING;

INSERT INTO "Part" ("PartID", "InventreeID")
VALUES
  (1, NULL),
  (2, NULL)
ON CONFLICT ("PartID") DO NOTHING;

INSERT INTO "BinSlot" ("BinID", "SlotNr", "PartID")
VALUES
  (1, 1, 0),
  (2, 2, 1),
  (2, 1, 0)
ON CONFLICT ("BinID", "SlotNr") DO NOTHING;

INSERT INTO "GridPos" ("GridPosID", "X", "Y", "BinID", "GridID")
VALUES
  (1, 0, 0, 1, 1),
  (2, 1, 0, 1, 1),
  (3, 0, 1, 2, 1)
ON CONFLICT ("GridPosID") DO NOTHING;



-- Location
SELECT setval(
    pg_get_serial_sequence('"Location"', 'LocationID'),
    COALESCE((SELECT MAX("LocationID") FROM "Location"), 1),
    true
);

-- Grid
SELECT setval(
    pg_get_serial_sequence('"Grid"', 'GridID'),
    COALESCE((SELECT MAX("GridID") FROM "Grid"), 1),
    true
);

-- BinType
SELECT setval(
    pg_get_serial_sequence('"BinType"', 'BinTypeID'),
    COALESCE((SELECT MAX("BinTypeID") FROM "BinType"), 1),
    true
);

-- Bin
SELECT setval(
    pg_get_serial_sequence('"Bin"', 'BinID'),
    COALESCE((SELECT MAX("BinID") FROM "Bin"), 1),
    true
);

-- Part
SELECT setval(
    pg_get_serial_sequence('"Part"', 'PartID'),
    COALESCE((SELECT MAX("PartID") FROM "Part"), 1),
    true
);

-- GridPos
SELECT setval(
    pg_get_serial_sequence('"GridPos"', 'GridPosID'),
    COALESCE((SELECT MAX("GridPosID") FROM "GridPos"), 1),
    true
);